### ISSUE TITLE
[QUEST] Magic Carpet Ride

### ISSUE THREAD

**Issue by xtracripper** [xtracripper/everfresh#44]
[Status: Pending]

Quest: Magic Carpet Ride

Location (cords if able): Warsong Hold - Borean Tundra

NPC/Objects Involved: Yanni - Magic Carpet

Item(s) Involved: Thorium's Charm of Earth

Description of issue: 
The carpet doesn't fly. It glides over the ground. Which means you'll aggro "Kel'Thuzad, Archlich of Naxxramas, esteemed Lich Lord of the Plaguelands, Commander of the Dread Necropolis, Master and Founder of the Cult of the Damned, formerly of the Council of Six, Creator of the Abomination, Summoner of Archimonde the Defiler, Betrayer of Humanity, Hearthstone Enthusiast, and Majordomo to the Lich King". Which kills you and makes the quest not completeable. Which locks you out of the quest chain at the beach.

Expected behavior:
Arrive at your location alive.

Steps to reproduce problem or avoid bug: 
Get quest, equip lance, jump on Stabled Campaign Warhorse, walk over Boneguard Footman 

Notes: It goes to shit at the Plains of Nasam

**Comment by RemoteDefinition** [comment]
Even more on this:

Once killed by KT if you release it'll resurrect you at the graveyard and launch you up in the air, killing yourself when you land. You can go to your body and resurrect, it doesn't seem to kill you infinitely.

**Comment by xtracripper** [comment]
Potential easy fix here, carpet may have the common (and easily remedied) flight bug. Tagging this as Next.
