### ISSUE TITLE
[Custom Scaling] Tenacity Buff Stacks

### ISSUE THREAD

**Issue by valens14** [xtracripper/everfresh#83]
When doing OS10 we had 6 people inside and properly had 4 stacks.  1 person DCd while inside while trash clearing and wasn't back so we went ahead and pulled the boss.  Since there were only 5 of us left we all properly had 5 stacks.  The 6th person logged back in mid fight with sartharion and he was able to join the fight since he was still inside but everyone still had 5 stacks of tenacity even though we now had 6 people and should have been reduced to 4 stacks.  My guess is that the stacks probably dont update while in combat or an encounter is in progress.

**Comment by xtracripper** [comment]
Fixed
